import Head from 'next/head'
import React, { useState } from 'react'

export default function index() {
    
    const [data, setData] = useState([]);

    const fetchData = async () => {
        const req = await fetch("api/get_data");
        const data = await req.json();
        setData(data);
        console.log("data"+data)
        return data;
    };
    



  return (
    <>
        <Head>
            <title>Project BD | Admin</title>
            <meta
                name="description"
                content="Generated by create next app"
            />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>




        </main>
    </>
  )
}
